services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    env_file:
      - .env

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: VEnEheqMBjLNbIErIZwCdDcmbklGd1FsRL36rU6kZjg=
      MYSQL_DATABASE: todo-api
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
