# Use the official Node.js image as the base image
FROM node:20.11.1-alpine3.19

# Set the working directory in the container to /app
WORKDIR /app

# Copy the package.json file into the container at /app
COPY package.json yarn.lock /app/

# Install the dependencies and make the folder
RUN yarn install

# Copy the rest of the application code into the container
COPY . /app

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run the app when the container launches
CMD ["yarn", "run","start:dev"]