services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - DATABASE_URL=mysql://root:VEnEheqMBjLNbIErIZwCdDcmbklGd1FsRL36rU6kZjg=@host.docker.internal:3306/todo-api?schema=public
      - JWT_SECRET=HhotqQgTYOfZO0xKtn0ZrHopx+FvIUOCepMAHduDaI4=
    command: /bin/sh -c "yarn install && yarn start:dev"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: VEnEheqMBjLNbIErIZwCdDcmbklGd1FsRL36rU6kZjg=
      MYSQL_DATABASE: todo-api
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
